//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APD65_63011212019Entities : DbContext
    {
        public APD65_63011212019Entities()
            : base("name=APD65_63011212019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billx> Billxes { get; set; }
        public virtual DbSet<Customerx> Customerxes { get; set; }
        public virtual DbSet<Emplopeex> Emplopeexes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Productx> Productxes { get; set; }
        public virtual DbSet<TypeProduct> TypeProducts { get; set; }
        public virtual DbSet<ComboSet> ComboSets { get; set; }
        public virtual DbSet<ComboSetItem> ComboSetItems { get; set; }
    }
}
